[package]
name = "ml_wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
tract-onnx = {version = "0.21.11"}
image = "^0"
wasm-bindgen = "*"
console_error_panic_hook = "*"